# Generated by Django 4.1.4 on 2023-01-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="optional",
            field=models.BooleanField(default=True),
        ),
    ]
